### ISSUE TITLE
sugestão

### ISSUE THREAD

**Issue by osamuca** [tiaguinho/mat-color-picker#8]
olhei que você segue um padrão nos commits e queria saber se posso subir um plugin que já faz essa automatização, demorou?!

**Comment by osamuca** [comment]
@tiaguinho

**Comment by tiaguinho** [comment]
Hi @osamuca 
I'll take a look at this later and see the PR you have sent.

**Comment by osamuca** [comment]
@tiaguinho o que você acho da ideia?

**Comment by tiaguinho** [comment]
very nice!
thank for contribution @osamuca

**Comment by osamuca** [comment]
@tiaguinho se quiser depois escrevo como funciona esse padrão para quando tiver futuras contribuições a galera seguir o padrão e tbm posso fazer uma `release.sh`. o que acha?

**Comment by tiaguinho** [comment]
I'm already creating the contribution guidelines. But thank you.
